//////////////////////////////////////////////////////////////////
///                                                              /
///                          DO NOT EDIT                         /
///                                                              /
///              Manual changes will be overwritten.             /
///                                                              /
///        Generated by github.com/boundedinfinity/enumer        /
///                                                              /
//////////////////////////////////////////////////////////////////

package urier

import (
	"database/sql/driver"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"strings"
)

//////////////////////////////////////////////////////////////////
///                                                              /
///                             Type                             /
///                                                              /
//////////////////////////////////////////////////////////////////

type UriScheme string

//////////////////////////////////////////////////////////////////
///                                                              /
///                    Stringer implemenation                    /
///                                                              /
//////////////////////////////////////////////////////////////////

func (t UriScheme) String() string {
	return string(t)
}

//////////////////////////////////////////////////////////////////
///                                                              /
///             JSON marshal/unmarshal implemenation             /
///                                                              /
//////////////////////////////////////////////////////////////////

func (t UriScheme) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(t))
}

func (t *UriScheme) UnmarshalJSON(data []byte) error {
	var s string

	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	found, err := UriSchemes.Parse(s)

	if err != nil {
		return err
	}

	*t = found
	return nil
}

//////////////////////////////////////////////////////////////////
///                                                              /
///             YAML marshal/unmarshal implemenation             /
///                                                              /
//////////////////////////////////////////////////////////////////

func (t UriScheme) MarshalYAML() (interface{}, error) {
	return string(t), nil
}

func (t *UriScheme) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string

	if err := unmarshal(&s); err != nil {
		return err
	}

	found, err := UriSchemes.Parse(s)

	if err != nil {
		return err
	}

	*t = found
	return nil
}

//////////////////////////////////////////////////////////////////
///                                                              /
///              XML marshal/unmarshal implemenation             /
///                                                              /
//////////////////////////////////////////////////////////////////

func (t UriScheme) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.EncodeElement(string(t), start)
}

func (t *UriScheme) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var s string

	if err := d.DecodeElement(&s, &start); err != nil {
		return err
	}

	found, err := UriSchemes.Parse(s)

	if err != nil {
		return err
	}

	*t = found
	return nil
}

//////////////////////////////////////////////////////////////////
///                                                              /
///              SQL marshal/unmarshal implemenation             /
///                                                              /
//////////////////////////////////////////////////////////////////

func (t UriScheme) Value() (driver.Value, error) {
	return string(t), nil
}

func (t *UriScheme) Scan(value interface{}) error {
	if value == nil {
		return UriSchemes.errf(value)
	}

	dv, err := driver.String.ConvertValue(value)

	if err != nil {
		return err
	}

	s, ok := dv.(string)

	if !ok {
		return UriSchemes.errf(value)
	}

	found, err := UriSchemes.Parse(s)

	if err != nil {
		return err
	}

	*t = found
	return nil
}

//////////////////////////////////////////////////////////////////
///                                                              /
///                       Companion struct                       /
///                                                              /
//////////////////////////////////////////////////////////////////

var UriSchemes = uriSchemes{
	Err:                        fmt.Errorf("invalid UriScheme"),
	Invalid:                    UriScheme("invalid"),
	Aaa:                        UriScheme("aaa"),
	Aaas:                       UriScheme("aaas"),
	About:                      UriScheme("about"),
	Acap:                       UriScheme("acap"),
	Acct:                       UriScheme("acct"),
	Acr:                        UriScheme("acr"),
	Adiumxtra:                  UriScheme("adiumxtra"),
	Afp:                        UriScheme("afp"),
	Afs:                        UriScheme("afs"),
	Apt:                        UriScheme("apt"),
	Attachment:                 UriScheme("attachment"),
	Aw:                         UriScheme("aw"),
	Amss:                       UriScheme("amss"),
	Barion:                     UriScheme("barion"),
	Beshare:                    UriScheme("beshare"),
	Bitcoin:                    UriScheme("bitcoin"),
	Blob:                       UriScheme("blob"),
	Bolo:                       UriScheme("bolo"),
	Callto:                     UriScheme("callto"),
	Cap:                        UriScheme("cap"),
	Chrome:                     UriScheme("chrome"),
	ChromeExtension:            UriScheme("chrome-extension"),
	ComEventbriteAttendee:      UriScheme("com-eventbrite-attendee"),
	Cid:                        UriScheme("cid"),
	Coaps:                      UriScheme("coaps"),
	Conten:                     UriScheme("conten"),
	Crid:                       UriScheme("crid"),
	Cvs:                        UriScheme("cvs"),
	Dab:                        UriScheme("dab"),
	Data:                       UriScheme("data"),
	Dav:                        UriScheme("dav"),
	Dict:                       UriScheme("dict"),
	DlnaPlaysingle:             UriScheme("dlna-playsingle"),
	DlnaPlaycontainer:          UriScheme("dlna-playcontainer"),
	Dns:                        UriScheme("dns"),
	Dntp:                       UriScheme("dntp"),
	Doi:                        UriScheme("doi"),
	Drm:                        UriScheme("drm"),
	Dtn:                        UriScheme("dtn"),
	Dvb:                        UriScheme("dvb"),
	Ed2k:                       UriScheme("ed2k"),
	Example:                    UriScheme("example"),
	Facetime:                   UriScheme("facetime"),
	Fax:                        UriScheme("fax"),
	Feed:                       UriScheme("feed"),
	File:                       UriScheme("file"),
	Filesystem:                 UriScheme("filesystem"),
	Finger:                     UriScheme("finger"),
	Fish:                       UriScheme("fish"),
	Fm:                         UriScheme("fm"),
	Ftp:                        UriScheme("ftp"),
	Gemini:                     UriScheme("gemini"),
	Geo:                        UriScheme("geo"),
	Gg:                         UriScheme("gg"),
	Git:                        UriScheme("git"),
	Gizmoproject:               UriScheme("gizmoproject"),
	Go:                         UriScheme("go"),
	Gopher:                     UriScheme("gopher"),
	Gtalk:                      UriScheme("gtalk"),
	H323:                       UriScheme("h323"),
	Http:                       UriScheme("http"),
	Https:                      UriScheme("https"),
	Iax:                        UriScheme("iax"),
	Icap:                       UriScheme("icap"),
	Icon:                       UriScheme("icon"),
	Im:                         UriScheme("im"),
	Imap:                       UriScheme("imap"),
	Info:                       UriScheme("info"),
	Iotdisco:                   UriScheme("iotdisco"),
	Ipn:                        UriScheme("ipn"),
	Ipp:                        UriScheme("ipp"),
	Ipps:                       UriScheme("ipps"),
	Irc:                        UriScheme("irc"),
	Irc6:                       UriScheme("irc6"),
	Ircs:                       UriScheme("ircs"),
	Iris:                       UriScheme("iris"),
	IrisBeep:                   UriScheme("iris.beep"),
	IrisXpc:                    UriScheme("iris.xpc"),
	IrisXpcs:                   UriScheme("iris.xpcs"),
	IrisLws:                    UriScheme("iris.lws"),
	Itms:                       UriScheme("itms"),
	Jabber:                     UriScheme("jabber"),
	Jar:                        UriScheme("jar"),
	Jms:                        UriScheme("jms"),
	Keyparc:                    UriScheme("keyparc"),
	Lastfm:                     UriScheme("lastfm"),
	Ldap:                       UriScheme("ldap"),
	Ldaps:                      UriScheme("ldaps"),
	Magnet:                     UriScheme("magnet"),
	Mailserver:                 UriScheme("mailserver"),
	Mailto:                     UriScheme("mailto"),
	Maps:                       UriScheme("maps"),
	Market:                     UriScheme("market"),
	Message:                    UriScheme("message"),
	Mid:                        UriScheme("mid"),
	Mms:                        UriScheme("mms"),
	Modem:                      UriScheme("modem"),
	MsHelp:                     UriScheme("ms-help"),
	MsSettings:                 UriScheme("ms-settings"),
	MsSettingsAirplanemode:     UriScheme("ms-settings-airplanemode"),
	MsSettingsBluetooth:        UriScheme("ms-settings-bluetooth"),
	MsSettingsCamera:           UriScheme("ms-settings-camera"),
	MsSettingsCellular:         UriScheme("ms-settings-cellular"),
	MsSettingsCloudstorage:     UriScheme("ms-settings-cloudstorage"),
	MsSettingsEmailandaccounts: UriScheme("ms-settings-emailandaccounts"),
	MsSettingsLanguage:         UriScheme("ms-settings-language"),
	MsSettingsLocation:         UriScheme("ms-settings-location"),
	MsSettingsLock:             UriScheme("ms-settings-lock"),
	MsSettingsNfctransactions:  UriScheme("ms-settings-nfctransactions"),
	MsSettingsNotifications:    UriScheme("ms-settings-notifications"),
	MsSettingsPower:            UriScheme("ms-settings-power"),
	MsSettingsPrivacy:          UriScheme("ms-settings-privacy"),
	MsSettingsProximity:        UriScheme("ms-settings-proximity"),
	MsSettingsScreenrotation:   UriScheme("ms-settings-screenrotation"),
	MsSettingsWifi:             UriScheme("ms-settings-wifi"),
	MsSettingsWorkplace:        UriScheme("ms-settings-workplace"),
	Msnim:                      UriScheme("msnim"),
	Msrp:                       UriScheme("msrp"),
	Msrps:                      UriScheme("msrps"),
	Mtqp:                       UriScheme("mtqp"),
	Mumble:                     UriScheme("mumble"),
	Mupdate:                    UriScheme("mupdate"),
	Mvn:                        UriScheme("mvn"),
	News:                       UriScheme("news"),
	Nfs:                        UriScheme("nfs"),
	Ni:                         UriScheme("ni"),
	Nih:                        UriScheme("nih"),
	Nntp:                       UriScheme("nntp"),
	Oid:                        UriScheme("oid"),
	Opaquelocktoken:            UriScheme("opaquelocktoken"),
	Openpgp4fpr:                UriScheme("openpgp4fpr"),
	Pack:                       UriScheme("pack"),
	Palm:                       UriScheme("palm"),
	Paparazzi:                  UriScheme("paparazzi"),
	Payto:                      UriScheme("payto"),
	Pkcs11:                     UriScheme("pkcs11"),
	Platform:                   UriScheme("platform"),
	Pop:                        UriScheme("pop"),
	Pres:                       UriScheme("pres"),
	Prospero:                   UriScheme("prospero"),
	Proxy:                      UriScheme("proxy"),
	Psyc:                       UriScheme("psyc"),
	Query:                      UriScheme("query"),
	Redis:                      UriScheme("redis"),
	Rediss:                     UriScheme("rediss"),
	Reload:                     UriScheme("reload"),
	Res:                        UriScheme("res"),
	Resource:                   UriScheme("resource"),
	Rmi:                        UriScheme("rmi"),
	Rsync:                      UriScheme("rsync"),
	Rtmfp:                      UriScheme("rtmfp"),
	Rtmp:                       UriScheme("rtmp"),
	Rtsp:                       UriScheme("rtsp"),
	S3:                         UriScheme("s3"),
	Secondlife:                 UriScheme("secondlife"),
	Service:                    UriScheme("service"),
	Session:                    UriScheme("session"),
	Sftp:                       UriScheme("sftp"),
	Sgn:                        UriScheme("sgn"),
	Shc:                        UriScheme("shc"),
	Shttp:                      UriScheme("shttp"),
	Sieve:                      UriScheme("sieve"),
	Sip:                        UriScheme("sip"),
	Sips:                       UriScheme("sips"),
	Skype:                      UriScheme("skype"),
	Smb:                        UriScheme("smb"),
	Sms:                        UriScheme("sms"),
	Snews:                      UriScheme("snews"),
	Snmp:                       UriScheme("snmp"),
	SoapBeep:                   UriScheme("soap.beep"),
	SoapBeeps:                  UriScheme("soap.beeps"),
	Soldat:                     UriScheme("soldat"),
	Spotify:                    UriScheme("spotify"),
	Ssh:                        UriScheme("ssh"),
	Steam:                      UriScheme("steam"),
	Stun:                       UriScheme("stun"),
	Stuns:                      UriScheme("stuns"),
	Svn:                        UriScheme("svn"),
	Tag:                        UriScheme("tag"),
	Teamspeak:                  UriScheme("teamspeak"),
	Tel:                        UriScheme("tel"),
	Telnet:                     UriScheme("telnet"),
	Tftp:                       UriScheme("tftp"),
	Things:                     UriScheme("things"),
	Thismessage:                UriScheme("thismessage"),
	Tn3270:                     UriScheme("tn3270"),
	Tip:                        UriScheme("tip"),
	Turn:                       UriScheme("turn"),
	Turns:                      UriScheme("turns"),
	Tv:                         UriScheme("tv"),
	Udp:                        UriScheme("udp"),
	Unreal:                     UriScheme("unreal"),
	Urn:                        UriScheme("urn"),
	Ut2004:                     UriScheme("ut2004"),
	Vemmi:                      UriScheme("vemmi"),
	Ventrilo:                   UriScheme("ventrilo"),
	Videotex:                   UriScheme("videotex"),
	ViewSource:                 UriScheme("view-source"),
	Vnc:                        UriScheme("vnc"),
	Wais:                       UriScheme("wais"),
	Webcal:                     UriScheme("webcal"),
	Ws:                         UriScheme("ws"),
	Wss:                        UriScheme("wss"),
	Wtai:                       UriScheme("wtai"),
	Wyciwyg:                    UriScheme("wyciwyg"),
	Xcon:                       UriScheme("xcon"),
	XconUserid:                 UriScheme("xcon-userid"),
	Xfire:                      UriScheme("xfire"),
	XmlrpcBeep:                 UriScheme("xmlrpc.beep"),
	XmlrpcBeeps:                UriScheme("xmlrpc.beeps"),
	Xmpp:                       UriScheme("xmpp"),
	Xri:                        UriScheme("xri"),
	Ymsgr:                      UriScheme("ymsgr"),
	Z3950:                      UriScheme("z39.50"),
	Z3950r:                     UriScheme("z39.50r"),
	Z3950s:                     UriScheme("z39.50s"),
	Admin:                      UriScheme("admin"),
	App:                        UriScheme("app"),
	Javascript:                 UriScheme("javascript"),
	Jdbc:                       UriScheme("jdbc"),
	Msteams:                    UriScheme("msteams"),
	MsAccess:                   UriScheme("ms-access"),
	MsExcel:                    UriScheme("ms-excel"),
	MsInfopath:                 UriScheme("ms-infopath"),
	MsPowerpoint:               UriScheme("ms-powerpoint"),
	MsProject:                  UriScheme("ms-project"),
	MsPublisher:                UriScheme("ms-publisher"),
	MsSpd:                      UriScheme("ms-spd"),
	MsVisio:                    UriScheme("ms-visio"),
	MsWord:                     UriScheme("ms-word"),
	Odbc:                       UriScheme("odbc"),
	Rdar:                       UriScheme("rdar"),
	Trueconf:                   UriScheme("trueconf"),
	Slack:                      UriScheme("slack"),
	Stratum:                    UriScheme("stratum"),
	Zoommtg:                    UriScheme("zoommtg"),
	Zoomus:                     UriScheme("zoomus"),
}

type uriSchemes struct {
	Err                        error
	errf                       func(any, ...UriScheme) error
	parseMap                   map[UriScheme][]string
	Invalid                    UriScheme
	Aaa                        UriScheme
	Aaas                       UriScheme
	About                      UriScheme
	Acap                       UriScheme
	Acct                       UriScheme
	Acr                        UriScheme
	Adiumxtra                  UriScheme
	Afp                        UriScheme
	Afs                        UriScheme
	Apt                        UriScheme
	Attachment                 UriScheme
	Aw                         UriScheme
	Amss                       UriScheme
	Barion                     UriScheme
	Beshare                    UriScheme
	Bitcoin                    UriScheme
	Blob                       UriScheme
	Bolo                       UriScheme
	Callto                     UriScheme
	Cap                        UriScheme
	Chrome                     UriScheme
	ChromeExtension            UriScheme
	ComEventbriteAttendee      UriScheme
	Cid                        UriScheme
	Coaps                      UriScheme
	Conten                     UriScheme
	Crid                       UriScheme
	Cvs                        UriScheme
	Dab                        UriScheme
	Data                       UriScheme
	Dav                        UriScheme
	Dict                       UriScheme
	DlnaPlaysingle             UriScheme
	DlnaPlaycontainer          UriScheme
	Dns                        UriScheme
	Dntp                       UriScheme
	Doi                        UriScheme
	Drm                        UriScheme
	Dtn                        UriScheme
	Dvb                        UriScheme
	Ed2k                       UriScheme
	Example                    UriScheme
	Facetime                   UriScheme
	Fax                        UriScheme
	Feed                       UriScheme
	File                       UriScheme
	Filesystem                 UriScheme
	Finger                     UriScheme
	Fish                       UriScheme
	Fm                         UriScheme
	Ftp                        UriScheme
	Gemini                     UriScheme
	Geo                        UriScheme
	Gg                         UriScheme
	Git                        UriScheme
	Gizmoproject               UriScheme
	Go                         UriScheme
	Gopher                     UriScheme
	Gtalk                      UriScheme
	H323                       UriScheme
	Http                       UriScheme
	Https                      UriScheme
	Iax                        UriScheme
	Icap                       UriScheme
	Icon                       UriScheme
	Im                         UriScheme
	Imap                       UriScheme
	Info                       UriScheme
	Iotdisco                   UriScheme
	Ipn                        UriScheme
	Ipp                        UriScheme
	Ipps                       UriScheme
	Irc                        UriScheme
	Irc6                       UriScheme
	Ircs                       UriScheme
	Iris                       UriScheme
	IrisBeep                   UriScheme
	IrisXpc                    UriScheme
	IrisXpcs                   UriScheme
	IrisLws                    UriScheme
	Itms                       UriScheme
	Jabber                     UriScheme
	Jar                        UriScheme
	Jms                        UriScheme
	Keyparc                    UriScheme
	Lastfm                     UriScheme
	Ldap                       UriScheme
	Ldaps                      UriScheme
	Magnet                     UriScheme
	Mailserver                 UriScheme
	Mailto                     UriScheme
	Maps                       UriScheme
	Market                     UriScheme
	Message                    UriScheme
	Mid                        UriScheme
	Mms                        UriScheme
	Modem                      UriScheme
	MsHelp                     UriScheme
	MsSettings                 UriScheme
	MsSettingsAirplanemode     UriScheme
	MsSettingsBluetooth        UriScheme
	MsSettingsCamera           UriScheme
	MsSettingsCellular         UriScheme
	MsSettingsCloudstorage     UriScheme
	MsSettingsEmailandaccounts UriScheme
	MsSettingsLanguage         UriScheme
	MsSettingsLocation         UriScheme
	MsSettingsLock             UriScheme
	MsSettingsNfctransactions  UriScheme
	MsSettingsNotifications    UriScheme
	MsSettingsPower            UriScheme
	MsSettingsPrivacy          UriScheme
	MsSettingsProximity        UriScheme
	MsSettingsScreenrotation   UriScheme
	MsSettingsWifi             UriScheme
	MsSettingsWorkplace        UriScheme
	Msnim                      UriScheme
	Msrp                       UriScheme
	Msrps                      UriScheme
	Mtqp                       UriScheme
	Mumble                     UriScheme
	Mupdate                    UriScheme
	Mvn                        UriScheme
	News                       UriScheme
	Nfs                        UriScheme
	Ni                         UriScheme
	Nih                        UriScheme
	Nntp                       UriScheme
	Oid                        UriScheme
	Opaquelocktoken            UriScheme
	Openpgp4fpr                UriScheme
	Pack                       UriScheme
	Palm                       UriScheme
	Paparazzi                  UriScheme
	Payto                      UriScheme
	Pkcs11                     UriScheme
	Platform                   UriScheme
	Pop                        UriScheme
	Pres                       UriScheme
	Prospero                   UriScheme
	Proxy                      UriScheme
	Psyc                       UriScheme
	Query                      UriScheme
	Redis                      UriScheme
	Rediss                     UriScheme
	Reload                     UriScheme
	Res                        UriScheme
	Resource                   UriScheme
	Rmi                        UriScheme
	Rsync                      UriScheme
	Rtmfp                      UriScheme
	Rtmp                       UriScheme
	Rtsp                       UriScheme
	S3                         UriScheme
	Secondlife                 UriScheme
	Service                    UriScheme
	Session                    UriScheme
	Sftp                       UriScheme
	Sgn                        UriScheme
	Shc                        UriScheme
	Shttp                      UriScheme
	Sieve                      UriScheme
	Sip                        UriScheme
	Sips                       UriScheme
	Skype                      UriScheme
	Smb                        UriScheme
	Sms                        UriScheme
	Snews                      UriScheme
	Snmp                       UriScheme
	SoapBeep                   UriScheme
	SoapBeeps                  UriScheme
	Soldat                     UriScheme
	Spotify                    UriScheme
	Ssh                        UriScheme
	Steam                      UriScheme
	Stun                       UriScheme
	Stuns                      UriScheme
	Svn                        UriScheme
	Tag                        UriScheme
	Teamspeak                  UriScheme
	Tel                        UriScheme
	Telnet                     UriScheme
	Tftp                       UriScheme
	Things                     UriScheme
	Thismessage                UriScheme
	Tn3270                     UriScheme
	Tip                        UriScheme
	Turn                       UriScheme
	Turns                      UriScheme
	Tv                         UriScheme
	Udp                        UriScheme
	Unreal                     UriScheme
	Urn                        UriScheme
	Ut2004                     UriScheme
	Vemmi                      UriScheme
	Ventrilo                   UriScheme
	Videotex                   UriScheme
	ViewSource                 UriScheme
	Vnc                        UriScheme
	Wais                       UriScheme
	Webcal                     UriScheme
	Ws                         UriScheme
	Wss                        UriScheme
	Wtai                       UriScheme
	Wyciwyg                    UriScheme
	Xcon                       UriScheme
	XconUserid                 UriScheme
	Xfire                      UriScheme
	XmlrpcBeep                 UriScheme
	XmlrpcBeeps                UriScheme
	Xmpp                       UriScheme
	Xri                        UriScheme
	Ymsgr                      UriScheme
	Z3950                      UriScheme
	Z3950r                     UriScheme
	Z3950s                     UriScheme
	Admin                      UriScheme
	App                        UriScheme
	Javascript                 UriScheme
	Jdbc                       UriScheme
	Msteams                    UriScheme
	MsAccess                   UriScheme
	MsExcel                    UriScheme
	MsInfopath                 UriScheme
	MsPowerpoint               UriScheme
	MsProject                  UriScheme
	MsPublisher                UriScheme
	MsSpd                      UriScheme
	MsVisio                    UriScheme
	MsWord                     UriScheme
	Odbc                       UriScheme
	Rdar                       UriScheme
	Trueconf                   UriScheme
	Slack                      UriScheme
	Stratum                    UriScheme
	Zoommtg                    UriScheme
	Zoomus                     UriScheme
}

func (t uriSchemes) Values() []UriScheme {
	return []UriScheme{
		UriSchemes.Aaa,
		UriSchemes.Aaas,
		UriSchemes.About,
		UriSchemes.Acap,
		UriSchemes.Acct,
		UriSchemes.Acr,
		UriSchemes.Adiumxtra,
		UriSchemes.Afp,
		UriSchemes.Afs,
		UriSchemes.Apt,
		UriSchemes.Attachment,
		UriSchemes.Aw,
		UriSchemes.Amss,
		UriSchemes.Barion,
		UriSchemes.Beshare,
		UriSchemes.Bitcoin,
		UriSchemes.Blob,
		UriSchemes.Bolo,
		UriSchemes.Callto,
		UriSchemes.Cap,
		UriSchemes.Chrome,
		UriSchemes.ChromeExtension,
		UriSchemes.ComEventbriteAttendee,
		UriSchemes.Cid,
		UriSchemes.Coaps,
		UriSchemes.Conten,
		UriSchemes.Crid,
		UriSchemes.Cvs,
		UriSchemes.Dab,
		UriSchemes.Data,
		UriSchemes.Dav,
		UriSchemes.Dict,
		UriSchemes.DlnaPlaysingle,
		UriSchemes.DlnaPlaycontainer,
		UriSchemes.Dns,
		UriSchemes.Dntp,
		UriSchemes.Doi,
		UriSchemes.Drm,
		UriSchemes.Dtn,
		UriSchemes.Dvb,
		UriSchemes.Ed2k,
		UriSchemes.Example,
		UriSchemes.Facetime,
		UriSchemes.Fax,
		UriSchemes.Feed,
		UriSchemes.File,
		UriSchemes.Filesystem,
		UriSchemes.Finger,
		UriSchemes.Fish,
		UriSchemes.Fm,
		UriSchemes.Ftp,
		UriSchemes.Gemini,
		UriSchemes.Geo,
		UriSchemes.Gg,
		UriSchemes.Git,
		UriSchemes.Gizmoproject,
		UriSchemes.Go,
		UriSchemes.Gopher,
		UriSchemes.Gtalk,
		UriSchemes.H323,
		UriSchemes.Http,
		UriSchemes.Https,
		UriSchemes.Iax,
		UriSchemes.Icap,
		UriSchemes.Icon,
		UriSchemes.Im,
		UriSchemes.Imap,
		UriSchemes.Info,
		UriSchemes.Iotdisco,
		UriSchemes.Ipn,
		UriSchemes.Ipp,
		UriSchemes.Ipps,
		UriSchemes.Irc,
		UriSchemes.Irc6,
		UriSchemes.Ircs,
		UriSchemes.Iris,
		UriSchemes.IrisBeep,
		UriSchemes.IrisXpc,
		UriSchemes.IrisXpcs,
		UriSchemes.IrisLws,
		UriSchemes.Itms,
		UriSchemes.Jabber,
		UriSchemes.Jar,
		UriSchemes.Jms,
		UriSchemes.Keyparc,
		UriSchemes.Lastfm,
		UriSchemes.Ldap,
		UriSchemes.Ldaps,
		UriSchemes.Magnet,
		UriSchemes.Mailserver,
		UriSchemes.Mailto,
		UriSchemes.Maps,
		UriSchemes.Market,
		UriSchemes.Message,
		UriSchemes.Mid,
		UriSchemes.Mms,
		UriSchemes.Modem,
		UriSchemes.MsHelp,
		UriSchemes.MsSettings,
		UriSchemes.MsSettingsAirplanemode,
		UriSchemes.MsSettingsBluetooth,
		UriSchemes.MsSettingsCamera,
		UriSchemes.MsSettingsCellular,
		UriSchemes.MsSettingsCloudstorage,
		UriSchemes.MsSettingsEmailandaccounts,
		UriSchemes.MsSettingsLanguage,
		UriSchemes.MsSettingsLocation,
		UriSchemes.MsSettingsLock,
		UriSchemes.MsSettingsNfctransactions,
		UriSchemes.MsSettingsNotifications,
		UriSchemes.MsSettingsPower,
		UriSchemes.MsSettingsPrivacy,
		UriSchemes.MsSettingsProximity,
		UriSchemes.MsSettingsScreenrotation,
		UriSchemes.MsSettingsWifi,
		UriSchemes.MsSettingsWorkplace,
		UriSchemes.Msnim,
		UriSchemes.Msrp,
		UriSchemes.Msrps,
		UriSchemes.Mtqp,
		UriSchemes.Mumble,
		UriSchemes.Mupdate,
		UriSchemes.Mvn,
		UriSchemes.News,
		UriSchemes.Nfs,
		UriSchemes.Ni,
		UriSchemes.Nih,
		UriSchemes.Nntp,
		UriSchemes.Oid,
		UriSchemes.Opaquelocktoken,
		UriSchemes.Openpgp4fpr,
		UriSchemes.Pack,
		UriSchemes.Palm,
		UriSchemes.Paparazzi,
		UriSchemes.Payto,
		UriSchemes.Pkcs11,
		UriSchemes.Platform,
		UriSchemes.Pop,
		UriSchemes.Pres,
		UriSchemes.Prospero,
		UriSchemes.Proxy,
		UriSchemes.Psyc,
		UriSchemes.Query,
		UriSchemes.Redis,
		UriSchemes.Rediss,
		UriSchemes.Reload,
		UriSchemes.Res,
		UriSchemes.Resource,
		UriSchemes.Rmi,
		UriSchemes.Rsync,
		UriSchemes.Rtmfp,
		UriSchemes.Rtmp,
		UriSchemes.Rtsp,
		UriSchemes.S3,
		UriSchemes.Secondlife,
		UriSchemes.Service,
		UriSchemes.Session,
		UriSchemes.Sftp,
		UriSchemes.Sgn,
		UriSchemes.Shc,
		UriSchemes.Shttp,
		UriSchemes.Sieve,
		UriSchemes.Sip,
		UriSchemes.Sips,
		UriSchemes.Skype,
		UriSchemes.Smb,
		UriSchemes.Sms,
		UriSchemes.Snews,
		UriSchemes.Snmp,
		UriSchemes.SoapBeep,
		UriSchemes.SoapBeeps,
		UriSchemes.Soldat,
		UriSchemes.Spotify,
		UriSchemes.Ssh,
		UriSchemes.Steam,
		UriSchemes.Stun,
		UriSchemes.Stuns,
		UriSchemes.Svn,
		UriSchemes.Tag,
		UriSchemes.Teamspeak,
		UriSchemes.Tel,
		UriSchemes.Telnet,
		UriSchemes.Tftp,
		UriSchemes.Things,
		UriSchemes.Thismessage,
		UriSchemes.Tn3270,
		UriSchemes.Tip,
		UriSchemes.Turn,
		UriSchemes.Turns,
		UriSchemes.Tv,
		UriSchemes.Udp,
		UriSchemes.Unreal,
		UriSchemes.Urn,
		UriSchemes.Ut2004,
		UriSchemes.Vemmi,
		UriSchemes.Ventrilo,
		UriSchemes.Videotex,
		UriSchemes.ViewSource,
		UriSchemes.Vnc,
		UriSchemes.Wais,
		UriSchemes.Webcal,
		UriSchemes.Ws,
		UriSchemes.Wss,
		UriSchemes.Wtai,
		UriSchemes.Wyciwyg,
		UriSchemes.Xcon,
		UriSchemes.XconUserid,
		UriSchemes.Xfire,
		UriSchemes.XmlrpcBeep,
		UriSchemes.XmlrpcBeeps,
		UriSchemes.Xmpp,
		UriSchemes.Xri,
		UriSchemes.Ymsgr,
		UriSchemes.Z3950,
		UriSchemes.Z3950r,
		UriSchemes.Z3950s,
		UriSchemes.Admin,
		UriSchemes.App,
		UriSchemes.Javascript,
		UriSchemes.Jdbc,
		UriSchemes.Msteams,
		UriSchemes.MsAccess,
		UriSchemes.MsExcel,
		UriSchemes.MsInfopath,
		UriSchemes.MsPowerpoint,
		UriSchemes.MsProject,
		UriSchemes.MsPublisher,
		UriSchemes.MsSpd,
		UriSchemes.MsVisio,
		UriSchemes.MsWord,
		UriSchemes.Odbc,
		UriSchemes.Rdar,
		UriSchemes.Trueconf,
		UriSchemes.Slack,
		UriSchemes.Stratum,
		UriSchemes.Zoommtg,
		UriSchemes.Zoomus,
	}
}

func (t uriSchemes) ParseFrom(v string, items ...UriScheme) (UriScheme, error) {
	var found UriScheme
	var ok bool

	for _, item := range items {
		matchers, ok2 := t.parseMap[item]

		if !ok2 {
			continue
		}

		for _, matcher := range matchers {
			if v == matcher {
				found = item
				ok = true
				break
			}
		}

		if ok {
			break
		}
	}

	if !ok {
		return found, t.errf(v, items...)
	}

	return found, nil
}

func (t uriSchemes) Parse(v string) (UriScheme, error) {
	return t.ParseFrom(v, t.Values()...)
}

func (t uriSchemes) IsFrom(v string, items ...UriScheme) bool {
	_, err := t.ParseFrom(v, items...)
	return err == nil
}

func (t uriSchemes) Is(v string) bool {
	return t.IsFrom(v, t.Values()...)
}

//////////////////////////////////////////////////////////////////
///                                                              /
///                        Initialization                        /
///                                                              /
//////////////////////////////////////////////////////////////////

func init() {
	UriSchemes.parseMap = map[UriScheme][]string{
		UriSchemes.Aaa:                        {"aaa", "Aaa"},
		UriSchemes.Aaas:                       {"aaas", "Aaas"},
		UriSchemes.About:                      {"about", "About"},
		UriSchemes.Acap:                       {"acap", "Acap"},
		UriSchemes.Acct:                       {"acct", "Acct"},
		UriSchemes.Acr:                        {"acr", "Acr"},
		UriSchemes.Adiumxtra:                  {"adiumxtra", "Adiumxtra"},
		UriSchemes.Admin:                      {"admin", "Admin"},
		UriSchemes.Afp:                        {"afp", "Afp"},
		UriSchemes.Afs:                        {"afs", "Afs"},
		UriSchemes.Amss:                       {"amss", "Amss"},
		UriSchemes.App:                        {"app", "App"},
		UriSchemes.Apt:                        {"apt", "Apt"},
		UriSchemes.Attachment:                 {"attachment", "Attachment"},
		UriSchemes.Aw:                         {"aw", "Aw"},
		UriSchemes.Barion:                     {"barion", "Barion"},
		UriSchemes.Beshare:                    {"beshare", "Beshare"},
		UriSchemes.Bitcoin:                    {"bitcoin", "Bitcoin"},
		UriSchemes.Blob:                       {"blob", "Blob"},
		UriSchemes.Bolo:                       {"bolo", "Bolo"},
		UriSchemes.Callto:                     {"callto", "Callto"},
		UriSchemes.Cap:                        {"cap", "Cap"},
		UriSchemes.Chrome:                     {"chrome", "Chrome"},
		UriSchemes.ChromeExtension:            {"chrome-extension", "ChromeExtension"},
		UriSchemes.Cid:                        {"cid", "Cid"},
		UriSchemes.Coaps:                      {"coaps", "Coaps"},
		UriSchemes.ComEventbriteAttendee:      {"com-eventbrite-attendee", "ComEventbriteAttendee"},
		UriSchemes.Conten:                     {"conten", "Conten"},
		UriSchemes.Crid:                       {"crid", "Crid"},
		UriSchemes.Cvs:                        {"cvs", "Cvs"},
		UriSchemes.Dab:                        {"dab", "Dab"},
		UriSchemes.Data:                       {"data", "Data"},
		UriSchemes.Dav:                        {"dav", "Dav"},
		UriSchemes.Dict:                       {"dict", "Dict"},
		UriSchemes.DlnaPlaycontainer:          {"dlna-playcontainer", "DlnaPlaycontainer"},
		UriSchemes.DlnaPlaysingle:             {"dlna-playsingle", "DlnaPlaysingle"},
		UriSchemes.Dns:                        {"dns", "Dns"},
		UriSchemes.Dntp:                       {"dntp", "Dntp"},
		UriSchemes.Doi:                        {"doi", "Doi"},
		UriSchemes.Drm:                        {"drm", "Drm"},
		UriSchemes.Dtn:                        {"dtn", "Dtn"},
		UriSchemes.Dvb:                        {"dvb", "Dvb"},
		UriSchemes.Ed2k:                       {"ed2k", "Ed2k"},
		UriSchemes.Example:                    {"example", "Example"},
		UriSchemes.Facetime:                   {"facetime", "Facetime"},
		UriSchemes.Fax:                        {"fax", "Fax"},
		UriSchemes.Feed:                       {"feed", "Feed"},
		UriSchemes.File:                       {"file", "File"},
		UriSchemes.Filesystem:                 {"filesystem", "Filesystem"},
		UriSchemes.Finger:                     {"finger", "Finger"},
		UriSchemes.Fish:                       {"fish", "Fish"},
		UriSchemes.Fm:                         {"fm", "Fm"},
		UriSchemes.Ftp:                        {"ftp", "Ftp"},
		UriSchemes.Gemini:                     {"gemini", "Gemini"},
		UriSchemes.Geo:                        {"geo", "Geo"},
		UriSchemes.Gg:                         {"gg", "Gg"},
		UriSchemes.Git:                        {"git", "Git"},
		UriSchemes.Gizmoproject:               {"gizmoproject", "Gizmoproject"},
		UriSchemes.Go:                         {"go", "Go"},
		UriSchemes.Gopher:                     {"gopher", "Gopher"},
		UriSchemes.Gtalk:                      {"gtalk", "Gtalk"},
		UriSchemes.H323:                       {"h323", "H323"},
		UriSchemes.Http:                       {"http", "Http"},
		UriSchemes.Https:                      {"https", "Https"},
		UriSchemes.Iax:                        {"iax", "Iax"},
		UriSchemes.Icap:                       {"icap", "Icap"},
		UriSchemes.Icon:                       {"icon", "Icon"},
		UriSchemes.Im:                         {"im", "Im"},
		UriSchemes.Imap:                       {"imap", "Imap"},
		UriSchemes.Info:                       {"info", "Info"},
		UriSchemes.Iotdisco:                   {"iotdisco", "Iotdisco"},
		UriSchemes.Ipn:                        {"ipn", "Ipn"},
		UriSchemes.Ipp:                        {"ipp", "Ipp"},
		UriSchemes.Ipps:                       {"ipps", "Ipps"},
		UriSchemes.Irc:                        {"irc", "Irc"},
		UriSchemes.Irc6:                       {"irc6", "Irc6"},
		UriSchemes.Ircs:                       {"ircs", "Ircs"},
		UriSchemes.Iris:                       {"iris", "Iris"},
		UriSchemes.IrisBeep:                   {"iris.beep", "IrisBeep"},
		UriSchemes.IrisLws:                    {"iris.lws", "IrisLws"},
		UriSchemes.IrisXpc:                    {"iris.xpc", "IrisXpc"},
		UriSchemes.IrisXpcs:                   {"iris.xpcs", "IrisXpcs"},
		UriSchemes.Itms:                       {"itms", "Itms"},
		UriSchemes.Jabber:                     {"jabber", "Jabber"},
		UriSchemes.Jar:                        {"jar", "Jar"},
		UriSchemes.Javascript:                 {"javascript", "Javascript"},
		UriSchemes.Jdbc:                       {"jdbc", "Jdbc"},
		UriSchemes.Jms:                        {"jms", "Jms"},
		UriSchemes.Keyparc:                    {"keyparc", "Keyparc"},
		UriSchemes.Lastfm:                     {"lastfm", "Lastfm"},
		UriSchemes.Ldap:                       {"ldap", "Ldap"},
		UriSchemes.Ldaps:                      {"ldaps", "Ldaps"},
		UriSchemes.Magnet:                     {"magnet", "Magnet"},
		UriSchemes.Mailserver:                 {"mailserver", "Mailserver"},
		UriSchemes.Mailto:                     {"mailto", "Mailto"},
		UriSchemes.Maps:                       {"maps", "Maps"},
		UriSchemes.Market:                     {"market", "Market"},
		UriSchemes.Message:                    {"message", "Message"},
		UriSchemes.Mid:                        {"mid", "Mid"},
		UriSchemes.Mms:                        {"mms", "Mms"},
		UriSchemes.Modem:                      {"modem", "Modem"},
		UriSchemes.MsAccess:                   {"ms-access", "MsAccess"},
		UriSchemes.MsExcel:                    {"ms-excel", "MsExcel"},
		UriSchemes.MsHelp:                     {"ms-help", "MsHelp"},
		UriSchemes.MsInfopath:                 {"ms-infopath", "MsInfopath"},
		UriSchemes.MsPowerpoint:               {"ms-powerpoint", "MsPowerpoint"},
		UriSchemes.MsProject:                  {"ms-project", "MsProject"},
		UriSchemes.MsPublisher:                {"ms-publisher", "MsPublisher"},
		UriSchemes.MsSettings:                 {"ms-settings", "MsSettings"},
		UriSchemes.MsSettingsAirplanemode:     {"ms-settings-airplanemode", "MsSettingsAirplanemode"},
		UriSchemes.MsSettingsBluetooth:        {"ms-settings-bluetooth", "MsSettingsBluetooth"},
		UriSchemes.MsSettingsCamera:           {"ms-settings-camera", "MsSettingsCamera"},
		UriSchemes.MsSettingsCellular:         {"ms-settings-cellular", "MsSettingsCellular"},
		UriSchemes.MsSettingsCloudstorage:     {"ms-settings-cloudstorage", "MsSettingsCloudstorage"},
		UriSchemes.MsSettingsEmailandaccounts: {"ms-settings-emailandaccounts", "MsSettingsEmailandaccounts"},
		UriSchemes.MsSettingsLanguage:         {"ms-settings-language", "MsSettingsLanguage"},
		UriSchemes.MsSettingsLocation:         {"ms-settings-location", "MsSettingsLocation"},
		UriSchemes.MsSettingsLock:             {"ms-settings-lock", "MsSettingsLock"},
		UriSchemes.MsSettingsNfctransactions:  {"ms-settings-nfctransactions", "MsSettingsNfctransactions"},
		UriSchemes.MsSettingsNotifications:    {"ms-settings-notifications", "MsSettingsNotifications"},
		UriSchemes.MsSettingsPower:            {"ms-settings-power", "MsSettingsPower"},
		UriSchemes.MsSettingsPrivacy:          {"ms-settings-privacy", "MsSettingsPrivacy"},
		UriSchemes.MsSettingsProximity:        {"ms-settings-proximity", "MsSettingsProximity"},
		UriSchemes.MsSettingsScreenrotation:   {"ms-settings-screenrotation", "MsSettingsScreenrotation"},
		UriSchemes.MsSettingsWifi:             {"ms-settings-wifi", "MsSettingsWifi"},
		UriSchemes.MsSettingsWorkplace:        {"ms-settings-workplace", "MsSettingsWorkplace"},
		UriSchemes.MsSpd:                      {"ms-spd", "MsSpd"},
		UriSchemes.MsVisio:                    {"ms-visio", "MsVisio"},
		UriSchemes.MsWord:                     {"ms-word", "MsWord"},
		UriSchemes.Msnim:                      {"msnim", "Msnim"},
		UriSchemes.Msrp:                       {"msrp", "Msrp"},
		UriSchemes.Msrps:                      {"msrps", "Msrps"},
		UriSchemes.Msteams:                    {"msteams", "Msteams"},
		UriSchemes.Mtqp:                       {"mtqp", "Mtqp"},
		UriSchemes.Mumble:                     {"mumble", "Mumble"},
		UriSchemes.Mupdate:                    {"mupdate", "Mupdate"},
		UriSchemes.Mvn:                        {"mvn", "Mvn"},
		UriSchemes.News:                       {"news", "News"},
		UriSchemes.Nfs:                        {"nfs", "Nfs"},
		UriSchemes.Ni:                         {"ni", "Ni"},
		UriSchemes.Nih:                        {"nih", "Nih"},
		UriSchemes.Nntp:                       {"nntp", "Nntp"},
		UriSchemes.Odbc:                       {"odbc", "Odbc"},
		UriSchemes.Oid:                        {"oid", "Oid"},
		UriSchemes.Opaquelocktoken:            {"opaquelocktoken", "Opaquelocktoken"},
		UriSchemes.Openpgp4fpr:                {"openpgp4fpr", "Openpgp4fpr"},
		UriSchemes.Pack:                       {"pack", "Pack"},
		UriSchemes.Palm:                       {"palm", "Palm"},
		UriSchemes.Paparazzi:                  {"paparazzi", "Paparazzi"},
		UriSchemes.Payto:                      {"payto", "Payto"},
		UriSchemes.Pkcs11:                     {"pkcs11", "Pkcs11"},
		UriSchemes.Platform:                   {"platform", "Platform"},
		UriSchemes.Pop:                        {"pop", "Pop"},
		UriSchemes.Pres:                       {"pres", "Pres"},
		UriSchemes.Prospero:                   {"prospero", "Prospero"},
		UriSchemes.Proxy:                      {"proxy", "Proxy"},
		UriSchemes.Psyc:                       {"psyc", "Psyc"},
		UriSchemes.Query:                      {"query", "Query"},
		UriSchemes.Rdar:                       {"rdar", "Rdar"},
		UriSchemes.Redis:                      {"redis", "Redis"},
		UriSchemes.Rediss:                     {"rediss", "Rediss"},
		UriSchemes.Reload:                     {"reload", "Reload"},
		UriSchemes.Res:                        {"res", "Res"},
		UriSchemes.Resource:                   {"resource", "Resource"},
		UriSchemes.Rmi:                        {"rmi", "Rmi"},
		UriSchemes.Rsync:                      {"rsync", "Rsync"},
		UriSchemes.Rtmfp:                      {"rtmfp", "Rtmfp"},
		UriSchemes.Rtmp:                       {"rtmp", "Rtmp"},
		UriSchemes.Rtsp:                       {"rtsp", "Rtsp"},
		UriSchemes.S3:                         {"s3", "S3"},
		UriSchemes.Secondlife:                 {"secondlife", "Secondlife"},
		UriSchemes.Service:                    {"service", "Service"},
		UriSchemes.Session:                    {"session", "Session"},
		UriSchemes.Sftp:                       {"sftp", "Sftp"},
		UriSchemes.Sgn:                        {"sgn", "Sgn"},
		UriSchemes.Shc:                        {"shc", "Shc"},
		UriSchemes.Shttp:                      {"shttp", "Shttp"},
		UriSchemes.Sieve:                      {"sieve", "Sieve"},
		UriSchemes.Sip:                        {"sip", "Sip"},
		UriSchemes.Sips:                       {"sips", "Sips"},
		UriSchemes.Skype:                      {"skype", "Skype"},
		UriSchemes.Slack:                      {"slack", "Slack"},
		UriSchemes.Smb:                        {"smb", "Smb"},
		UriSchemes.Sms:                        {"sms", "Sms"},
		UriSchemes.Snews:                      {"snews", "Snews"},
		UriSchemes.Snmp:                       {"snmp", "Snmp"},
		UriSchemes.SoapBeep:                   {"soap.beep", "SoapBeep"},
		UriSchemes.SoapBeeps:                  {"soap.beeps", "SoapBeeps"},
		UriSchemes.Soldat:                     {"soldat", "Soldat"},
		UriSchemes.Spotify:                    {"spotify", "Spotify"},
		UriSchemes.Ssh:                        {"ssh", "Ssh"},
		UriSchemes.Steam:                      {"steam", "Steam"},
		UriSchemes.Stratum:                    {"stratum", "Stratum"},
		UriSchemes.Stun:                       {"stun", "Stun"},
		UriSchemes.Stuns:                      {"stuns", "Stuns"},
		UriSchemes.Svn:                        {"svn", "Svn"},
		UriSchemes.Tag:                        {"tag", "Tag"},
		UriSchemes.Teamspeak:                  {"teamspeak", "Teamspeak"},
		UriSchemes.Tel:                        {"tel", "Tel"},
		UriSchemes.Telnet:                     {"telnet", "Telnet"},
		UriSchemes.Tftp:                       {"tftp", "Tftp"},
		UriSchemes.Things:                     {"things", "Things"},
		UriSchemes.Thismessage:                {"thismessage", "Thismessage"},
		UriSchemes.Tip:                        {"tip", "Tip"},
		UriSchemes.Tn3270:                     {"tn3270", "Tn3270"},
		UriSchemes.Trueconf:                   {"trueconf", "Trueconf"},
		UriSchemes.Turn:                       {"turn", "Turn"},
		UriSchemes.Turns:                      {"turns", "Turns"},
		UriSchemes.Tv:                         {"tv", "Tv"},
		UriSchemes.Udp:                        {"udp", "Udp"},
		UriSchemes.Unreal:                     {"unreal", "Unreal"},
		UriSchemes.Urn:                        {"urn", "Urn"},
		UriSchemes.Ut2004:                     {"ut2004", "Ut2004"},
		UriSchemes.Vemmi:                      {"vemmi", "Vemmi"},
		UriSchemes.Ventrilo:                   {"ventrilo", "Ventrilo"},
		UriSchemes.Videotex:                   {"videotex", "Videotex"},
		UriSchemes.ViewSource:                 {"view-source", "ViewSource"},
		UriSchemes.Vnc:                        {"vnc", "Vnc"},
		UriSchemes.Wais:                       {"wais", "Wais"},
		UriSchemes.Webcal:                     {"webcal", "Webcal"},
		UriSchemes.Ws:                         {"ws", "Ws"},
		UriSchemes.Wss:                        {"wss", "Wss"},
		UriSchemes.Wtai:                       {"wtai", "Wtai"},
		UriSchemes.Wyciwyg:                    {"wyciwyg", "Wyciwyg"},
		UriSchemes.Xcon:                       {"xcon", "Xcon"},
		UriSchemes.XconUserid:                 {"xcon-userid", "XconUserid"},
		UriSchemes.Xfire:                      {"xfire", "Xfire"},
		UriSchemes.XmlrpcBeep:                 {"xmlrpc.beep", "XmlrpcBeep"},
		UriSchemes.XmlrpcBeeps:                {"xmlrpc.beeps", "XmlrpcBeeps"},
		UriSchemes.Xmpp:                       {"xmpp", "Xmpp"},
		UriSchemes.Xri:                        {"xri", "Xri"},
		UriSchemes.Ymsgr:                      {"ymsgr", "Ymsgr"},
		UriSchemes.Z3950:                      {"z39.50", "Z3950"},
		UriSchemes.Z3950r:                     {"z39.50r", "Z3950r"},
		UriSchemes.Z3950s:                     {"z39.50s", "Z3950s"},
		UriSchemes.Zoommtg:                    {"zoommtg", "Zoommtg"},
		UriSchemes.Zoomus:                     {"zoomus", "Zoomus"},
	}

	UriSchemes.errf = func(v any, items ...UriScheme) error {
		var xs []string

		for _, item := range items {
			if x, ok := UriSchemes.parseMap[item]; ok {
				xs = append(xs, x...)
			}
		}

		return fmt.Errorf(
			"%w: %v is not one of %s",
			UriSchemes.Err,
			v,
			strings.Join(xs, ","),
		)
	}
}
