//////////////////////////////////////////////////////////////////
///                                                              /
///                          DO NOT EDIT                         /
///                                                              /
///              Manual changes will be overwritten.             /
///                                                              /
///        Generated by github.com/boundedinfinity/enumer        /
///                                                              /
//////////////////////////////////////////////////////////////////

package caser

import (
	"database/sql/driver"
	"encoding/json"
	"encoding/xml"
	"strings"

	errorer "github.com/boundedinfinity/go-commoner/errorer"
)

//////////////////////////////////////////////////////////////////
///                                                              /
///                             Type                             /
///                                                              /
//////////////////////////////////////////////////////////////////

type Case string

func (t Case) String() string {
	return string(t)
}

func (t Case) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(t))
}

func (t *Case) UnmarshalJSON(data []byte) error {
	var s string

	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	found, err := Cases.Parse(s)

	if err != nil {
		return err
	}

	*t = found
	return nil
}

func (t Case) MarshalYAML() (interface{}, error) {
	return string(t), nil
}

func (t *Case) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string

	if err := unmarshal(&s); err != nil {
		return err
	}

	found, err := Cases.Parse(s)

	if err != nil {
		return err
	}

	*t = found
	return nil
}

func (t Case) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.EncodeElement(string(t), start)
}

func (t *Case) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var s string

	if err := d.DecodeElement(&s, &start); err != nil {
		return err
	}

	found, err := Cases.Parse(s)

	if err != nil {
		return err
	}

	*t = found
	return nil
}

func (t Case) Value() (driver.Value, error) {
	return string(t), nil
}

func (t *Case) Scan(value interface{}) error {
	if value == nil {
		return Cases.errf(value)
	}

	dv, err := driver.String.ConvertValue(value)

	if err != nil {
		return err
	}

	s, ok := dv.(string)

	if !ok {
		return Cases.errf(value)
	}

	found, err := Cases.Parse(s)

	if err != nil {
		return err
	}

	*t = found
	return nil
}

//////////////////////////////////////////////////////////////////
///                                                              /
///                       Companion struct                       /
///                                                              /
//////////////////////////////////////////////////////////////////

var Cases = cases{
	Err:        errorer.New("invalid CaseType"),
	Invalid:    Case("invalid"),
	Camel:      Case("camel"),
	Kebab:      Case("kebab"),
	KebabLower: Case("kebab-lower"),
	KebabUpper: Case("kebab-upper"),
	Pascal:     Case("pascal"),
	Phrase:     Case("phrase"),
	Snake:      Case("snake"),
	SnakeLower: Case("snake-lower"),
	SnakeUpper: Case("snake-upper"),
	Unknown:    Case("unknown"),
}

type cases struct {
	Err        error
	errf       func(...any) error
	parseMap   map[Case][]string
	Invalid    Case
	Camel      Case
	Kebab      Case
	KebabLower Case
	KebabUpper Case
	Pascal     Case
	Phrase     Case
	Snake      Case
	SnakeLower Case
	SnakeUpper Case
	Unknown    Case
}

func (t cases) Values() []Case {
	return []Case{
		Cases.Camel,
		Cases.Kebab,
		Cases.KebabLower,
		Cases.KebabUpper,
		Cases.Pascal,
		Cases.Phrase,
		Cases.Snake,
		Cases.SnakeLower,
		Cases.SnakeUpper,
		Cases.Unknown,
	}
}

func (t cases) ToStrings(items ...Case) []string {
	var results []string

	for _, item := range items {
		results = append(results, item.String())
	}

	return results
}

func (t cases) ParseFrom(v string, items ...Case) (Case, error) {
	found := t.Invalid
	var ok bool

	for _, item := range items {
		matchers, ok2 := t.parseMap[item]

		if !ok2 {
			continue
		}

		for _, matcher := range matchers {
			if v == matcher {
				found = item
				ok = true
				break
			}
		}

		if ok {
			break
		}
	}

	if !ok {
		list := strings.Join(t.ToStrings(items...), ",")
		return found, t.errf(v, list)
	}

	return found, nil
}

func (t cases) Parse(v string) (Case, error) {
	return t.ParseFrom(v, t.Values()...)
}

func (t cases) IsFrom(v string, items ...Case) bool {
	_, err := t.ParseFrom(v, items...)
	return err == nil
}

func (t cases) Is(v string) bool {
	return t.IsFrom(v, t.Values()...)
}

//////////////////////////////////////////////////////////////////
///                                                              /
///                        Initialization                        /
///                                                              /
//////////////////////////////////////////////////////////////////

var (
	ErrCaser   = errorer.New("caser error")
	errCaserFn = errorer.Func(ErrCaser)
)

func init() {
	Cases.parseMap = map[Case][]string{
		Cases.Camel:      {"camel", "Camel"},
		Cases.Kebab:      {"kebab", "Kebab"},
		Cases.KebabLower: {"kebab-lower", "KebabLower"},
		Cases.KebabUpper: {"kebab-upper", "KebabUpper"},
		Cases.Pascal:     {"pascal", "Pascal"},
		Cases.Phrase:     {"phrase", "Phrase"},
		Cases.Snake:      {"snake", "Snake"},
		Cases.SnakeLower: {"snake-lower", "SnakeLower"},
		Cases.SnakeUpper: {"snake-upper", "SnakeUpper"},
		Cases.Unknown:    {"unknown", "Unknown"},
	}
}
