//////////////////////////////////////////////////////////////////
///                                                              /
///                          DO NOT EDIT                         /
///                                                              /
///              Manual changes will be overwritten.             /
///                                                              /
///        Generated by github.com/boundedinfinity/enumer        /
///                                                              /
//////////////////////////////////////////////////////////////////

package measurement

import (
	"database/sql/driver"
	"encoding/json"
	"encoding/xml"
	errorer "github.com/boundedinfinity/go-commoner/errorer"
	"strings"
)

//////////////////////////////////////////////////////////////////
///                                                              /
///                             Type                             /
///                                                              /
//////////////////////////////////////////////////////////////////

type AreaUnit string

//////////////////////////////////////////////////////////////////
///                                                              /
///                    Stringer implemenation                    /
///                                                              /
//////////////////////////////////////////////////////////////////

func (t AreaUnit) String() string {
	return string(t)
}

//////////////////////////////////////////////////////////////////
///                                                              /
///             JSON marshal/unmarshal implemenation             /
///                                                              /
//////////////////////////////////////////////////////////////////

func (t AreaUnit) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(t))
}

func (t *AreaUnit) UnmarshalJSON(data []byte) error {
	var s string

	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	found, err := AreaUnits.Parse(s)

	if err != nil {
		return err
	}

	*t = found
	return nil
}

//////////////////////////////////////////////////////////////////
///                                                              /
///             YAML marshal/unmarshal implemenation             /
///                                                              /
//////////////////////////////////////////////////////////////////

func (t AreaUnit) MarshalYAML() (interface{}, error) {
	return string(t), nil
}

func (t *AreaUnit) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string

	if err := unmarshal(&s); err != nil {
		return err
	}

	found, err := AreaUnits.Parse(s)

	if err != nil {
		return err
	}

	*t = found
	return nil
}

//////////////////////////////////////////////////////////////////
///                                                              /
///              XML marshal/unmarshal implemenation             /
///                                                              /
//////////////////////////////////////////////////////////////////

func (t AreaUnit) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.EncodeElement(string(t), start)
}

func (t *AreaUnit) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var s string

	if err := d.DecodeElement(&s, &start); err != nil {
		return err
	}

	found, err := AreaUnits.Parse(s)

	if err != nil {
		return err
	}

	*t = found
	return nil
}

//////////////////////////////////////////////////////////////////
///                                                              /
///              SQL marshal/unmarshal implemenation             /
///                                                              /
//////////////////////////////////////////////////////////////////

func (t AreaUnit) Value() (driver.Value, error) {
	return string(t), nil
}

func (t *AreaUnit) Scan(value interface{}) error {
	if value == nil {
		return AreaUnits.errf(value)
	}

	dv, err := driver.String.ConvertValue(value)

	if err != nil {
		return err
	}

	s, ok := dv.(string)

	if !ok {
		return AreaUnits.errf(value)
	}

	found, err := AreaUnits.Parse(s)

	if err != nil {
		return err
	}

	*t = found
	return nil
}

//////////////////////////////////////////////////////////////////
///                                                              /
///                       Companion struct                       /
///                                                              /
//////////////////////////////////////////////////////////////////

var AreaUnits = areaUnits{
	Err:        errorer.New("invalid AreaUnit"),
	Invalid:    AreaUnit("invalid"),
	SquareMile: AreaUnit("square-mile"),
	Acre:       AreaUnit("acre"),
	Rood:       AreaUnit("rood"),
	SquareYard: AreaUnit("square-yard"),
	SquareFoot: AreaUnit("square-foot"),
	SquareInch: AreaUnit("square-inch"),
}

type areaUnits struct {
	Err        error
	errf       func(...any) error
	parseMap   map[AreaUnit][]string
	Invalid    AreaUnit
	SquareMile AreaUnit
	Acre       AreaUnit
	Rood       AreaUnit
	SquareYard AreaUnit
	SquareFoot AreaUnit
	SquareInch AreaUnit
}

func (t areaUnits) Values() []AreaUnit {
	return []AreaUnit{
		AreaUnits.SquareMile,
		AreaUnits.Acre,
		AreaUnits.Rood,
		AreaUnits.SquareYard,
		AreaUnits.SquareFoot,
		AreaUnits.SquareInch,
	}
}

func (t areaUnits) ToStrings(items ...AreaUnit) []string {
	var results []string

	for _, item := range items {
		results = append(results, item.String())
	}

	return results
}

func (t areaUnits) ParseFrom(v string, items ...AreaUnit) (AreaUnit, error) {
	found := t.Invalid
	var ok bool

	for _, item := range items {
		matchers, ok2 := t.parseMap[item]

		if !ok2 {
			continue
		}

		for _, matcher := range matchers {
			if v == matcher {
				found = item
				ok = true
				break
			}
		}

		if ok {
			break
		}
	}

	if !ok {
		list := strings.Join(t.ToStrings(items...), ",")
		return found, t.errf(v, list)
	}

	return found, nil
}

func (t areaUnits) Parse(v string) (AreaUnit, error) {
	return t.ParseFrom(v, t.Values()...)
}

func (t areaUnits) IsFrom(v string, items ...AreaUnit) bool {
	_, err := t.ParseFrom(v, items...)
	return err == nil
}

func (t areaUnits) Is(v string) bool {
	return t.IsFrom(v, t.Values()...)
}

//////////////////////////////////////////////////////////////////
///                                                              /
///                        Initialization                        /
///                                                              /
//////////////////////////////////////////////////////////////////

func init() {
	AreaUnits.parseMap = map[AreaUnit][]string{
		AreaUnits.Acre:       {"acre", "Acre"},
		AreaUnits.Rood:       {"rood", "Rood"},
		AreaUnits.SquareFoot: {"square-foot", "SquareFoot"},
		AreaUnits.SquareInch: {"square-inch", "SquareInch"},
		AreaUnits.SquareMile: {"square-mile", "SquareMile"},
		AreaUnits.SquareYard: {"square-yard", "SquareYard"},
	}

	AreaUnits.errf = AreaUnits.Err.(*errorer.Errorer).FormatFn("%v is not one of %s")
}
