package measurement

import (
	"database/sql/driver"
	"encoding/xml"
	"fmt"
	enumer "github.com/boundedinfinity/enumer"
)

//************************************************************************************
//*                                                                                  *
//* ===== DO NOT EDIT =====                                                          *
//* Manual changes will be overwritten.                                              *
//* Generated by github.com/boundedinfinity/enumer                                   *
//*                                                                                  *
//************************************************************************************

type MetricUnit string

func (t MetricUnit) String() string {
	return string(t)
}

// /////////////////////////////////////////////////////////////////
//  JSON serialization
// /////////////////////////////////////////////////////////////////

func (t MetricUnit) MarshalJSON() ([]byte, error) {
	return enumer.MarshalJSON(t)
}

func (t *MetricUnit) UnmarshalJSON(data []byte) error {
	return enumer.UnmarshalJSON(data, t, MetricUnits.Parse)
}

// /////////////////////////////////////////////////////////////////
//  YAML serialization
// /////////////////////////////////////////////////////////////////

func (t MetricUnit) MarshalYAML() (interface{}, error) {
	return enumer.MarshalYAML(t)
}

func (t *MetricUnit) UnmarshalYAML(unmarshal func(interface{}) error) error {
	return enumer.UnmarshalYAML(unmarshal, t, MetricUnits.Parse)
}

// /////////////////////////////////////////////////////////////////
//  XML serialization
// /////////////////////////////////////////////////////////////////

func (t MetricUnit) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return enumer.MarshalXML(t, e, start)
}

func (t *MetricUnit) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return enumer.UnmarshalXML(t, MetricUnits.Parse, d, start)
}

// /////////////////////////////////////////////////////////////////
//  SQL serialization
// /////////////////////////////////////////////////////////////////

func (t MetricUnit) Value() (driver.Value, error) {
	return enumer.Value(t)
}

func (t *MetricUnit) Scan(value interface{}) error {
	return enumer.Scan(value, t, MetricUnits.Parse)
}

// /////////////////////////////////////////////////////////////////
//  Companion
// /////////////////////////////////////////////////////////////////

type metricUnits struct {
	Tera   MetricUnit
	Giga   MetricUnit
	Mega   MetricUnit
	Kilo   MetricUnit
	Hecto  MetricUnit
	Deca   MetricUnit
	Unit   MetricUnit
	Deci   MetricUnit
	Centi  MetricUnit
	Milli  MetricUnit
	Micro  MetricUnit
	Nano   MetricUnit
	Pico   MetricUnit
	Values []MetricUnit
	Err    error
}

var MetricUnits = metricUnits{

	Centi: MetricUnit("centi"),
	Deca:  MetricUnit("deca"),
	Deci:  MetricUnit("deci"),
	Err:   fmt.Errorf("invalid MetricUnit"),
	Giga:  MetricUnit("giga"),
	Hecto: MetricUnit("hecto"),
	Kilo:  MetricUnit("kilo"),
	Mega:  MetricUnit("mega"),
	Micro: MetricUnit("micro"),
	Milli: MetricUnit("milli"),
	Nano:  MetricUnit("nano"),
	Pico:  MetricUnit("pico"),
	Tera:  MetricUnit("tera"),
	Unit:  MetricUnit("unit"),
}

func init() {
	MetricUnits.Values = []MetricUnit{
		MetricUnits.Tera,
		MetricUnits.Giga,
		MetricUnits.Mega,
		MetricUnits.Kilo,
		MetricUnits.Hecto,
		MetricUnits.Deca,
		MetricUnits.Unit,
		MetricUnits.Deci,
		MetricUnits.Centi,
		MetricUnits.Milli,
		MetricUnits.Micro,
		MetricUnits.Nano,
		MetricUnits.Pico,
	}
}

func (t metricUnits) newErr(a any, values ...MetricUnit) error {
	return fmt.Errorf(
		"invalid %w value '%v'. Must be one of %v",
		MetricUnits.Err,
		a,
		enumer.Join(values, ", "))
}

func (t metricUnits) ParseFrom(v string, values ...MetricUnit) (MetricUnit, error) {
	var found MetricUnit
	var ok bool

	for _, value := range values {
		if enumer.IsEq[string, MetricUnit](v)(value) {
			found = value
			ok = true
			break
		}
	}

	if !ok {
		return found, t.newErr(v, values...)
	}

	return found, nil
}

func (t metricUnits) Parse(v string) (MetricUnit, error) {
	return t.ParseFrom(v, MetricUnits.Values...)
}

func (t metricUnits) IsFrom(v string, values ...MetricUnit) bool {
	for _, value := range values {
		if enumer.IsEq[string, MetricUnit](v)(value) {
			return true
		}
	}
	return false
}

func (t metricUnits) Is(v string) bool {
	return t.IsFrom(v, MetricUnits.Values...)
}
