package utf8

import "github.com/boundedinfinity/go-commoner/slicer"

var (
	UPPERCASE = []Utf8Char{
		UPPERCASE_A,
		UPPERCASE_B,
		UPPERCASE_C,
		UPPERCASE_D,
		UPPERCASE_E,
		UPPERCASE_F,
		UPPERCASE_G,
		UPPERCASE_H,
		UPPERCASE_I,
		UPPERCASE_J,
		UPPERCASE_K,
		UPPERCASE_L,
		UPPERCASE_M,
		UPPERCASE_N,
		UPPERCASE_O,
		UPPERCASE_P,
		UPPERCASE_Q,
		UPPERCASE_R,
		UPPERCASE_S,
		UPPERCASE_T,
		UPPERCASE_U,
		UPPERCASE_V,
		UPPERCASE_W,
		UPPERCASE_X,
		UPPERCASE_Y,
		UPPERCASE_Z,
	}

	LOWERCASE = []Utf8Char{
		LOWERCASE_A,
		LOWERCASE_B,
		LOWERCASE_C,
		LOWERCASE_D,
		LOWERCASE_E,
		LOWERCASE_F,
		LOWERCASE_G,
		LOWERCASE_H,
		LOWERCASE_I,
		LOWERCASE_J,
		LOWERCASE_K,
		LOWERCASE_L,
		LOWERCASE_M,
		LOWERCASE_N,
		LOWERCASE_O,
		LOWERCASE_P,
		LOWERCASE_Q,
		LOWERCASE_R,
		LOWERCASE_S,
		LOWERCASE_T,
		LOWERCASE_U,
		LOWERCASE_V,
		LOWERCASE_W,
		LOWERCASE_X,
		LOWERCASE_Y,
		LOWERCASE_Z,
	}

	NUMBERS = []Utf8Char{
		NUMBER_ZERO,
		NUMBER_ONE,
		NUMBER_TWO,
		NUMBER_THREE,
		NUMBER_FOUR,
		NUMBER_FIVE,
		NUMBER_SIX,
		NUMBER_SEVEN,
		NUMBER_EIGHT,
		NUMBER_NINE,
	}

	WHITESPACE = []Utf8Char{
		BACKSPACE,
		HORIZONTAL_TAB,
		LINE_FEED,
		VERTICAL_TAB,
		FORM_FEED,
		CARRIAGE_RETURN,
		SPACE,
	}

	SYMBOLS = []Utf8Char{
		EXCLAMATION_MARK,
		DOUBLE_QUOTE,
		NUMBER,
		DOLLAR,
		PERCENT,
		AMPERSAND,
		SINGLE_QUOTE,
		LEFT_PARENTHESIS,
		RIGHT_PARENTHESIS,
		ASTERISK,
		PLUS,
		COMMA,
		MINUS,
		PERIOD,
		SLASH,
		COLON,
		SEMICOLON,
		LESS_THAN,
		EQUAL_SIGN,
		GREATER_THAN,
		QUESTION_MARK,
		AT_SIGN,
		LEFT_SQUARE_BRACKET,
		BACKSLASH,
		RIGHT_SQUARE_BRACKET,
		CARET,
		UNDERSCORE,
		GRAVE,
		LEFT_CURLY_BRACKET,
		VERTICAL_BAR,
		RIGHT_CURLY_BRACKET,
		TILDE,
	}
)

var (
	LETTERS              = []Utf8Char{}
	VISIBLE_CHARACTERS   = []Utf8Char{}
	WORD_CHARACTERS      = []Utf8Char{}
	PRINTABLE_CHARACTERS = []Utf8Char{}
)

func init() {
	LETTERS = slicer.Flatten(UPPERCASE, LOWERCASE)
	WORD_CHARACTERS = slicer.Flatten(UPPERCASE, LOWERCASE, NUMBERS)
	VISIBLE_CHARACTERS = slicer.Flatten(UPPERCASE, LOWERCASE, NUMBERS, SYMBOLS)
	PRINTABLE_CHARACTERS = slicer.Flatten(UPPERCASE, LOWERCASE, NUMBERS, SYMBOLS, WHITESPACE)
}
